<?php

use App\Models\User;

// use Collector\Features;

return [

    /*
    |--------------------------------------------------------------------------
    | Collector Path
    |--------------------------------------------------------------------------
    |
    | This configuration option determines the URI at which the Collector billing
    | portal is available. You are free to change this URI to a value that
    | you prefer. You shall link to this location from your application.
    |
    */

    'path' => 'billing',

    'secret' => env('PAYSTACK_SECRET_KEY'),

    /*
    |--------------------------------------------------------------------------
    | Collector Middleware
    |--------------------------------------------------------------------------
    |
    | These are the middleware that requests to the Collector billing portal must
    | pass through before being accepted. Typically, the default list that
    | is defined below should be suitable for most Laravel applications.
    |
    */

    'middleware' => ['web', 'auth'],

    /*
    |--------------------------------------------------------------------------
    | Branding
    |--------------------------------------------------------------------------
    |
    | These configuration values allow you to customize the branding of the
    | billing portal, including the primary color and the logo that will
    | be displayed within the billing portal. This logo value must be
    | the absolute path to an SVG logo within the local filesystem.
    |
    */

    // 'brand' =>  [
    //     'logo' => realpath(__DIR__.'/../public/svg/billing-logo.svg'),
    //     'color' => 'bg-gray-800',
    // ],

    /*
    |--------------------------------------------------------------------------
    | Proration Behavior
    |--------------------------------------------------------------------------
    |
    | This value determines if charges are prorated when making adjustments
    | to a plan such as incrementing or decrementing the quantity of the
    | plan. This also determines proration behavior if changing plans.
    |
    */

    'prorates' => true,

    /*
    |--------------------------------------------------------------------------
    | Collector Date Format
    |--------------------------------------------------------------------------
    |
    | This date format will be utilized by Collector to format dates in various
    | locations within the billing portal, such as while showing invoice
    | dates. You should customize the format based on your own locale.
    |
    */

    'date_format' => 'F j, Y',

    /*
    |--------------------------------------------------------------------------
    | Features
    |--------------------------------------------------------------------------
    |
    | Some of Collector's features are optional. You may disable the features by
    | removing them from this array. By removing features from this array
    | you can customize your Collector experience for your own application.
    |
    */

    'features' => [
        // Features::billingAddressCollection(['required' => true]),
        // Features::mustAcceptTerms(),
        // Features::euVatCollection(['home-country' => 'BE']),
        // Features::receiptEmails(['custom-addresses' => true]),
        // Features::paymentNotificationEmails(),
    ],

    /*
    |--------------------------------------------------------------------------
    | Receipt Configuration
    |--------------------------------------------------------------------------
    |
    | The following configuration options allow you to configure the data that
    | appears in PDF receipts generated by Collector. Typically, this data will
    | include a company name as well as your company contact information.
    |
    */

    'receipt_data' => [
        'vendor' => 'Your Product',
        'product' => 'Your Product',
        'street' => '111 Example St.',
        'location' => 'Los Angeles, CA',
        'phone' => '555-555-5555',
    ],

    /*
    |--------------------------------------------------------------------------
    | Collector Collectables
    |--------------------------------------------------------------------------
    |
    | Below you may define collectable entities supported by your Collector driven
    | application. The paystack edition of Collector currently only supports a
    | single collectable model entity (team, user, etc.) per application.
    |
    | In addition to defining your collectable entity, you may also define its
    | plans and the plan's features, including a short description of it
    | as well as a "bullet point" listing of its distinctive features.
    |
    */

    'currency' => env('COLLECTOR_CURRENCY', 'GHS'),

    'collectables' => [
        'user' => [
            'model' => User::class,
            'trial_days' => 5,
            'default_interval' => 'monthly',
            'plans' => [
                [
                    'name' => 'Basic',
                    'description' => 'This is a short, human friendly description of the plan.',
                    'monthly_id' => 'PLN_worid7k3e8v5afz',
                    'yearly_incentive' => 'Save 10%',
                    'yearly_id' => 'PLN_2y8oe4r1gx7gakr',
                    'features' => [
                        'Feature 1',
                        'Feature 2',
                        'Feature 3',
                    ],
                    'options' => [

                    ],
                ],
                [
                    'name' => 'Standard',
                    'description' => 'This is a short, human friendly description of the plan.',
                    'monthly_id' => 'PLN_wc54sx7clavvy6d',
                    'yearly_id' => 'PLN_b9kvd76fufw4vu9',
                    'yearly_incentive' => 'Save 10%',
                    'features' => [
                        'Feature 1',
                        'Feature 2',
                        'Feature 3',
                    ],
                ],
                [
                    'name' => 'Premium',
                    'description' => 'This is a short, human friendly description of the plan.',
                    'monthly_id' => 'PLN_g47cv05s5jsz29k',
                    'yearly_id' => null,
                    'features' => [
                        'Feature 1',
                        'Feature 2',
                        'Feature 3',
                    ],
                ],
                [
                    'name' => 'Unlimited',
                    'description' => 'This is a short, human friendly description of the plan.',
                    'monthly_id' => 'PLN_l2qz2ab1wjhh4yx',
                    'yearly_id' => null,
                    'features' => [
                        'Feature 1',
                        'Feature 2',
                        'Feature 3',
                    ],
                ],
            ],

        ],
    ],

    /**
     * This will be shown on the cancelation modal
     */
    'cancelation' => [
        'heading' => 'Are you sure you want to cancel your subscription?',
        'subText' => 'Once your subscription is cancelled, all of its resources and related data will be permanently deleted.',
        'reasonLabel' => 'Please why you canceling',
    ],
];
